config/routes.rb
Rails.application.routes.draw do
  root "kittens#index"
  resources :kittens
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :get_kitten, only: [:show, :edit, :destroy]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to @kitten, notice: 'Kitten created successfully.'
    else
      render :new, notice: 'Something went wrong.'
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update(kitten_params)
    if @kitten.save
      redirect_to @kitten, notice: 'Kitten updated successfully.'
    else
      render :edit, notice: 'Something went wrong.'
    end
  end

  def destroy
    if @kitten.destroy
      redirect_to kittens_url, notice: 'Kitten destroyed. How could you?!'
    else
      redirect_to kittens_url, notice: 'Kitten not found in database.'
    end
  end

  private

  def get_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :age %>
  <%= f.text_field :age %>
  <br />
  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %>
  <br />
  <%= f.label :softness %>
  <%= f.text_field :softness %>
  <br />
  <%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<%= render partial: 'form' %>
<%= link_to "Back", kitten_path %>

app/views/kittens/index.html.erb
<h1>Kittens:</h1>
<ul>
<% @kittens.each do |k|%>
  <li><%= link_to( k.name, kitten_path(k)) %></li>
<% end %>
<div class="options">
</div>
</ul>
<%= link_to "Create", new_kitten_path %>

app/views/kittens/new.html.erb
<%= render partial: "form" %>
<%= link_to "Back", kittens_path %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<h2>Attributes:</h2>
<p><strong>Age:</strong> <%= @kitten.age %></p>
<p><strong>Cuteness:</strong> <%= @kitten.cuteness %>/10</p>
<p><strong>Softness:</strong> <%= @kitten.softness %>/10</p>
<%= link_to "Edit", edit_kitten_path %>
<%= link_to "Delete", @kitten, method: :delete, data: {confirm: "Are you sure you want to destroy the kitten?"}   %>
<%= link_to "Back", kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TopKittenApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %> </div>
    <% end %>
    <%= yield %>
  </body>
</html>